spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/v3demo
    username: root
    password: asdasd
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true
  flyway:
    enabled: true
    baseline-version: 1
    baseline-on-migrate: true