spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/v3demo
    username: root
    password: asdasd
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true