spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:${MYSQL_URL}
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    flyway:
      enabled: false